export type Language = 'en' | 'pt' | 'zh' | 'es' | 'de';

export const languages: Record<Language, string> = {
  en: 'English',
  pt: 'Português',
  zh: '中文 (Mandarin)',
  es: 'Español',
  de: 'Deutsch',
};

type Translations = {
  [key: string]: { [lang in Language]: string };
};

const translations: Translations = {
    "app.title": {
        en: "Quote Generator",
        pt: "Gerador de Orçamentos",
        zh: "报价生成器",
        es: "Generador de Cotizaciones",
        de: "Angebotsgenerator"
    },
    "tabs.dashboard": { en: "Dashboard", pt: "Dashboard", zh: "仪表板", es: "Panel", de: "Dashboard" },
    "tabs.budget": { en: "Budget", pt: "Orçamento", zh: "预算", es: "Presupuesto", de: "Budget" },
    "tabs.calculator": { en: "Calculator", pt: "Cálculo", zh: "计算器", es: "Calculadora", de: "Rechner" },
    "tabs.pricing": { en: "Pricing", pt: "Precificação", zh: "定价", es: "Precios", de: "Preisgestaltung" },
    "tabs.subscriptions": { en: "Subscriptions", pt: "Assinaturas", zh: "订阅", es: "Suscripciones", de: "Abonnements" },
    "tabs.settings": { en: "Settings", pt: "Configurações", zh: "设置", es: "Configuración", de: "Einstellungen" },

    "dashboard.title": { en: "Dashboard", pt: "Dashboard", zh: "仪表板", es: "Panel", de: "Dashboard" },
    "dashboard.totalCost": { en: "Total Cost", pt: "Custo Total", zh: "总成本", es: "Costo Total", de: "Gesamtkosten" },
    "dashboard.finalValue": { en: "Final Value (w/ Markup)", pt: "Valor Final (c/ Markup)", zh: "最终价值（含加价）", es: "Valor Final (con Margen)", de: "Endwert (mit Aufschlag)" },
    "dashboard.totalItems": { en: "Total Items", pt: "Total de Itens", zh: "项目总数", es: "Total de Artículos", de: "Artikel insgesamt" },
    "dashboard.costBySector": { en: "Cost by Sector", pt: "Custo por Setor", zh: "按部门划分的成本", es: "Costo por Sector", de: "Kosten nach Sektor" },
    "dashboard.top5Expensive": { en: "Top 5 Most Expensive Items", pt: "Top 5 Itens Mais Caros", zh: "最昂贵的5个项目", es: "Top 5 Artículos Más Caros", de: "Top 5 teuerste Artikel" },
    "dashboard.empty.title": { en: "Your dashboard is empty", pt: "Seu dashboard está vazio", zh: "您的仪表板是空的", es: "Tu panel está vacío", de: "Ihr Dashboard ist leer" },
    "dashboard.empty.description": { en: "Add items to your budget to see the analysis here.", pt: "Adicione itens ao seu orçamento para ver as análises aqui.", zh: "将项目添加到您的预算中以在此处查看分析。", es: "Agrega artículos a tu presupuesto para ver el análisis aquí.", de: "Fügen Sie Artikel zu Ihrem Budget hinzu, um die Analyse hier zu sehen." },

    "budget.newBudget": { en: "New Budget", pt: "Novo Orçamento", zh: "新预算", es: "Nuevo Presupuesto", de: "Neues Budget" },
    "budget.titlePlaceholder": { en: "Budget Title", pt: "Título do Orçamento", zh: "预算标题", es: "Título del Presupuesto", de: "Budget-Titel" },
    "budget.table.description": { en: "Description", pt: "Descrição", zh: "描述", es: "Descripción", de: "Beschreibung" },
    "budget.table.sector": { en: "Sector", pt: "Setor", zh: "部门", es: "Sector", de: "Sektor" },
    "budget.table.quantity": { en: "Qty.", pt: "Qtd.", zh: "数量", es: "Cant.", de: "Menge" },
    "budget.table.unitCost": { en: "Unit Price (Cost)", pt: "Preço Unit. (Custo)", zh: "单价（成本）", es: "Precio Unit. (Costo)", de: "Stückpreis (Kosten)" },
    "budget.table.unitFinal": { en: "Unit Price (Final)", pt: "Preço Unit. (Final)", zh: "单价（最终）", es: "Precio Unit. (Final)", de: "Stückpreis (Endgültig)" },
    "budget.table.subtotal": { en: "Subtotal (Final)", pt: "Subtotal (Final)", zh: "小计（最终）", es: "Subtotal (Final)", de: "Zwischensumme (Endgültig)" },
    "budget.table.actions": { en: "Actions", pt: "Ações", zh: "操作", es: "Acciones", de: "Aktionen" },
    "budget.table.noItems": { en: "No items in the budget. Start by adding items in the 'Calculator' tab.", pt: "Nenhum item no orçamento. Comece adicionando itens na aba 'Cálculo'.", zh: "预算中没有项目。从“计算器”选项卡开始添加项目。", es: "No hay artículos en el presupuesto. Comienza agregando artículos en la pestaña 'Calculadora'.", de: "Keine Artikel im Budget. Beginnen Sie mit dem Hinzufügen von Artikeln im Tab 'Rechner'." },
    "budget.summary.title": { en: "Financial Summary", pt: "Resumo Financeiro", zh: "财务摘要", es: "Resumen Financiero", de: "Finanzübersicht" },
    "budget.summary.totalCost": { en: "Total Cost:", pt: "Custo Total:", zh: "总成本:", es: "Costo Total:", de: "Gesamtkosten:" },
    "budget.summary.markup": { en: "Markup ({markupPercentage}%):", pt: "Markup ({markupPercentage}%):", zh: "加价 ({markupPercentage}%):", es: "Margen ({markupPercentage}%):", de: "Aufschlag ({markupPercentage}%):" },
    "budget.summary.finalValue": { en: "Final Value:", pt: "Valor Final:", zh: "最终价值:", es: "Valor Final:", de: "Endwert:" },
    "budget.actions.title": { en: "Actions", pt: "Ações", zh: "操作", es: "Acciones", de: "Aktionen" },
    "budget.actions.autoPrice": { en: "Auto-Pricing", pt: "Precificação Automática", zh: "自动定价", es: "Fijación de Precios Automática", de: "Automatische Preisgestaltung" },
    "budget.actions.customizePdf": { en: "Customize PDF", pt: "Customizar PDF", zh: "自定义PDF", es: "Personalizar PDF", de: "PDF anpassen" },
    "budget.actions.exportPdf": { en: "Export PDF", pt: "Exportar PDF", zh: "导出PDF", es: "Exportar PDF", de: "PDF exportieren" },
    "budget.actions.exportXlsx": { en: "Export Excel", pt: "Exportar Excel", zh: "导出Excel", es: "Exportar Excel", de: "Excel exportieren" },
    "budget.myBudgets.title": { en: "My Budgets", pt: "Meus Orçamentos", zh: "我的预算", es: "Mis Presupuestos", de: "Meine Budgets" },
    "budget.myBudgets.load": { en: "Load", pt: "Carregar", zh: "加载", es: "Cargar", de: "Laden" },
    "budget.myBudgets.delete": { en: "Delete", pt: "Excluir", zh: "删除", es: "Eliminar", de: "Löschen" },
    "budget.myBudgets.new": { en: "New", pt: "Novo", zh: "新建", es: "Nuevo", de: "Neu" },
    "budget.myBudgets.save": { en: "Save", pt: "Salvar", zh: "保存", es: "Guardar", de: "Speichern" },
    "budget.deleteConfirmation": { en: "Are you sure you want to delete this budget? This action cannot be undone.", pt: "Tem certeza que deseja excluir este orçamento? Esta ação não pode ser desfeita.", zh: "您确定要删除此预算吗？此操作无法撤销。", es: "¿Estás seguro de que quieres eliminar este presupuesto? Esta acción no se puede deshacer.", de: "Sind Sie sicher, dass Sie dieses Budget löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden." },

    "calculator.general": { en: "General", pt: "Geral", zh: "通用", es: "General", de: "Allgemein" },
    "calculator.electrical": { en: "Electrical", pt: "Elétrica", zh: "电气", es: "Eléctrica", de: "Elektrisch" },
    "calculator.generalCalculations": { en: "General Calculations (Formulas)", pt: "Cálculos Gerais (Fórmulas)", zh: "通用计算（公式）", es: "Cálculos Generales (Fórmulas)", de: "Allgemeine Berechnungen (Formeln)" },
    "calculator.addGroup.placeholder": { en: "New Group Name", pt: "Nome do Novo Grupo", zh: "新组名", es: "Nombre del Nuevo Grupo", de: "Neuer Gruppenname" },
    "calculator.save": { en: "Save", pt: "Salvar", zh: "保存", es: "Guardar", de: "Speichern" },
    "calculator.cancel": { en: "Cancel", pt: "Cancelar", zh: "取消", es: "Cancelar", de: "Abbrechen" },
    "calculator.addGroup.button": { en: "Add New Group", pt: "Adicionar Novo Grupo", zh: "添加新组", es: "Añadir Nuevo Grupo", de: "Neue Gruppe hinzufügen" },
    "calculator.deleteGroup.button": { en: "Delete Current Group", pt: "Excluir Grupo Atual", zh: "删除当前组", es: "Eliminar Grupo Actual", de: "Aktuelle Gruppe löschen" },
    "calculator.generalInfo": { en: "General Information", pt: "Informações Gerais", zh: "基本信息", es: "Información General", de: "Allgemeine Informationen" },
    "calculator.calculationParams": { en: "Calculation Parameters", pt: "Parâmetros de Cálculo", zh: "计算参数", es: "Parámetros de Cálculo", de: "Berechnungsparameter" },
    "calculator.noParams": { en: "No calculation parameters for this group.", pt: "Nenhum parâmetro de cálculo para este grupo.", zh: "该组没有计算参数。", es: "No hay parámetros de cálculo para este grupo.", de: "Keine Berechnungsparameter für diese Gruppe." },
    "calculator.results": { en: "Calculation Results", pt: "Resultados do Cálculo", zh: "计算结果", es: "Resultados del Cálculo", de: "Berechnungsergebnisse" },
    "calculator.error": { en: "Error", pt: "Erro", zh: "错误", es: "Error", de: "Fehler" },
    "calculator.customize": { en: "Customize Formulas and Variables", pt: "Personalizar Fórmulas e Variáveis", zh: "自定义公式和变量", es: "Personalizar Fórmulas y Variables", de: "Formeln und Variablen anpassen" },
    "calculator.groupName": { en: "Calculation Group Name", pt: "Nome do Grupo de Cálculo", zh: "计算组名称", es: "Nombre del Grupo de Cálculo", de: "Name der Berechnungsgruppe" },
    "calculator.inputVars": { en: "Input Variables", pt: "Variáveis de Entrada", zh: "输入变量", es: "Variables de Entrada", de: "Eingabevariablen" },
    "calculator.codePlaceholder": { en: "Code (e.g., LG)", pt: "Código (ex: LG)", zh: "代码（例如 LG）", es: "Código (ej: LG)", de: "Code (z.B. LG)" },
    "calculator.descPlaceholder": { en: "Variable Description", pt: "Descrição da Variável", zh: "变量描述", es: "Descripción de la Variable", de: "Variablenbeschreibung" },
    "calculator.infoField": { en: "Info Field", pt: "Campo de Informação", zh: "信息字段", es: "Campo de Información", de: "Informationsfeld" },
    "calculator.linkInfo": { en: "Link to info to form the item name", pt: "Vincular a informações para formar o nome do item", zh: "链接到信息以形成项目名称", es: "Vincular a información para formar el nombre del artículo", de: "Mit Informationen verknüpfen, um den Artikelnamen zu bilden" },
    "calculator.noInfoToLink": { en: "No 'Info' to link.", pt: "Nenhuma 'Informação' para vincular.", zh: "没有可链接的“信息”。", es: "No hay 'Información' para vincular.", de: "Keine 'Info' zum Verknüpfen." },
    "calculator.addParam": { en: "+ Add Parameter", pt: "+ Adicionar Parâmetro", zh: "+ 添加参数", es: "+ Añadir Parámetro", de: "+ Parameter hinzufügen" },
    "calculator.addInfo": { en: "+ Add Information", pt: "+ Adicionar Informação", zh: "+ 添加信息", es: "+ Añadir Información", de: "+ Information hinzufügen" },
    "calculator.resultFormulas": { en: "Result Formulas", pt: "Fórmulas de Resultado", zh: "结果公式", es: "Fórmulas de Resultado", de: "Ergebnisformeln" },
    "calculator.itemNamePlaceholder": { en: "Final Item Name", pt: "Nome do Item Final", zh: "最终项目名称", es: "Nombre del Artículo Final", de: "Endgültiger Artikelname" },
    "calculator.formulaPlaceholder": { en: "Formula (e.g., [LG]*2)", pt: "Fórmula (ex: [LG]*2)", zh: "公式（例如 [LG]*2）", es: "Fórmula (ej: [LG]*2)", de: "Formel (z.B. [LG]*2)" },
    "calculator.unitPlaceholder": { en: "Unit (e.g., pc)", pt: "Unidade (ex: un)", zh: "单位（例如 pc）", es: "Unidad (ej: un)", de: "Einheit (z.B. Stk)" },
    "calculator.addFormula": { en: "+ Add Formula", pt: "+ Adicionar Fórmula", zh: "+ 添加公式", es: "+ Añadir Fórmula", de: "+ Formel hinzufügen" },
    "calculator.formulaHint": { en: "Tip: Use `()` or `{}` for grouping. Standard math order is respected.", pt: "Dica: Use `()` ou `{}` para agrupar operações. A ordem matemática padrão é respeitada.", zh: "提示：使用 `()` 或 `{}` 进行分组。遵循标准数学顺序。", es: "Consejo: Use `()` o `{}` para agrupar. Se respeta el orden matemático estándar.", de: "Tipp: Verwenden Sie `()` oder `{}`, um zu gruppieren. Die Standard-Rechenreihenfolge wird beachtet." },
    "calculator.addToBudget": { en: "Add to Budget", pt: "Adicionar ao Orçamento", zh: "添加到预算", es: "Añadir al Presupuesto", de: "Zum Budget hinzufügen" },
    "calculator.clearFields": { en: "Clear Fields", pt: "Limpar Campos", zh: "清除字段", es: "Limpiar Campos", de: "Felder leeren" },
    "calculator.newGroup": { en: "New Group", pt: "Novo Grupo", zh: "新组", es: "Nuevo Grupo", de: "Neue Gruppe" },
    "calculator.newItem": { en: "New Item", pt: "Novo Item", zh: "新项目", es: "Nuevo Artículo", de: "Neuer Artikel" },
    "calculator.newInfo": { en: "New Information", pt: "Nova Informação", zh: "新信息", es: "Nueva Información", de: "Neue Information" },
    "calculator.newVariable": { en: "New Variable", pt: "Nova Variável", zh: "新变量", es: "Nueva Variable", de: "Neue Variable" },
    "calculator.cannotDeleteGroup": { en: "The only calculation group cannot be deleted.", pt: "Não é possível excluir o único grupo de cálculo.", zh: "无法删除唯一的计算组。", es: "No se puede eliminar el único grupo de cálculo.", de: "Die einzige Berechnungsgruppe kann nicht gelöscht werden." },
    "calculator.electrical.panels": { en: "Panels Assembly", pt: "Montagem de Quadros", zh: "配电盘组装", es: "Montaje de Paneles", de: "Schaltschrankbau" },
    "calculator.electrical.wiring": { en: "Wiring & Terminals", pt: "Fiação e Terminais", zh: "布线和端子", es: "Cableado y Terminales", de: "Verdrahtung & Klemmen" },
    "calculator.electrical.finishing": { en: "Finishing", pt: "Acabamento", zh: "收尾", es: "Acabado", de: "Fertigstellung" },
    "calculator.labor": { en: "Labor", pt: "Mão de Obra", zh: "人工", es: "Mano de Obra", de: "Arbeitskraft" },
    "calculator.labor.teamAndDuration": { en: "Team and Duration", pt: "Equipe e Duração", zh: "团队和工期", es: "Equipo y Duración", de: "Team und Dauer" },
    "calculator.labor.workTime": { en: "Work Time (days)", pt: "Tempo de Obra (dias)", zh: "工期（天）", es: "Tiempo de Trabajo (días)", de: "Arbeitszeit (Tage)" },
    "calculator.labor.description": { en: "Description", pt: "Descrição", zh: "描述", es: "Descripción", de: "Beschreibung" },
    "calculator.labor.technician": { en: "Technician", pt: "Técnico", zh: "技术员", es: "Técnico", de: "Techniker" },
    "calculator.labor.quantity": { en: "Quantity", pt: "Quantidade", zh: "数量", es: "Cantidad", de: "Anzahl" },
    "calculator.labor.dailyRate": { en: "Daily Rate (R$)", pt: "Diária (R$)", zh: "日薪 (R$)", es: "Tarifa Diaria (R$)", de: "Tagessatz (R$)" },
    "calculator.labor.addProfessional": { en: "+ Add Professional", pt: "+ Adicionar Profissional", zh: "+ 添加专业人员", es: "+ Añadir Profesional", de: "+ Fachkraft hinzufügen" },
    "calculator.labor.additionalCosts": { en: "Additional Costs (per day)", pt: "Custos Adicionais (por dia)", zh: "额外费用（每天）", es: "Costos Adicionales (por día)", de: "Zusätzliche Kosten (pro Tag)" },
    "calculator.labor.costSummary": { en: "Cost Summary", pt: "Resumo de Custos", zh: "成本摘要", es: "Resumen de Costos", de: "Kostenübersicht" },
    "calculator.labor.totalLabor": { en: "Total Labor", pt: "Total Mão de Obra", zh: "总人工", es: "Mano de Obra Total", de: "Gesamtarbeitskosten" },
    "calculator.labor.totalAdditionals": { en: "Total Additionals", pt: "Total Adicionais", zh: "总附加费用", es: "Total Adicionales", de: "Gesamte Zusatzkosten" },
    "calculator.labor.totalValue": { en: "Total Value", pt: "Valor Total", zh: "总价值", es: "Valor Total", de: "Gesamtwert" },
    "calculator.labor.dailyValue": { en: "Daily Value", pt: "Valor Diário", zh: "每日价值", es: "Valor Diario", de: "Tageswert" },
    "calculator.labor.additionals.noturno": { en: "Night Shift Premium", pt: "Adicional Noturno", zh: "夜班津贴", es: "Plus de Nocturnidad", de: "Nachtzuschlag" },
    "calculator.labor.additionals.veiculo": { en: "Vehicle", pt: "Veículo", zh: "车辆", es: "Vehículo", de: "Fahrzeug" },
    "calculator.labor.additionals.estadia": { en: "Accommodation", pt: "Estadia", zh: "住宿", es: "Alojamiento", de: "Unterkunft" },
    "calculator.labor.additionals.distancia": { en: "Distance Premium", pt: "Adicional de Distância", zh: "距离津贴", es: "Plus de Distancia", de: "Entfernungszuschlag" },
    "calculator.labor.additionals.refeicao": { en: "Meals", pt: "Refeição", zh: "膳食", es: "Comidas", de: "Mahlzeiten" },
    "calculator.labor.additionals.ferramentas": { en: "Tools", pt: "Ferramentas", zh: "工具", es: "Herramientas", de: "Werkzeuge" },
    "calculator.labor.additionals.andaime": { en: "Scaffolding", pt: "Andaime", zh: "脚手架", es: "Andamio", de: "Gerüst" },
    "calculator.labor.additionals.ptas": { en: "Aerial Work Platforms", pt: "PTAs", zh: "高空作业平台", es: "Plataformas de Trabajo Aéreo", de: "Arbeitsbühnen" },
    "calculator.labor.additionals.epis": { en: "PPE (Personal Protective Equipment)", pt: "EPIs", zh: "个人防护装备", es: "EPP (Equipo de Protección Personal)", de: "PSA (Persönliche Schutzausrüstung)" },
    "calculator.labor.additionals.certificacoes": { en: "Certifications (NR10, NR35)", pt: "Certificações (NR10, NR35)", zh: "认证 (NR10, NR35)", es: "Certificaciones (NR10, NR35)", de: "Zertifizierungen (NR10, NR35)" },
    "calculator.labor.totalLaborCost": { en: "Total Labor Cost", pt: "Custo Total de Mão de Obra", zh: "总人工成本", es: "Costo Total de Mano de Obra", de: "Gesamtarbeitskosten" },
    "calculator.labor.totalAdditionalCost": { en: "Total Additional Costs", pt: "Custos Adicionais Totais", zh: "总附加成本", es: "Costos Adicionales Totales", de: "Gesamte Zusatzkosten" },
    
    "pricing.title": { en: "Pricing Database", pt: "Base de Preços", zh: "定价数据库", es: "Base de Precios", de: "Preisdatenbank" },
    "pricing.description": { en: "Manage your price list here. You can add items manually or import a spreadsheet. This database will be used to automatically price your budget.", pt: "Gerencie sua lista de preços aqui. Você pode adicionar itens manualmente ou importar uma planilha. Esta base será usada para precificar seu orçamento automaticamente.", zh: "在这里管理您的价格表。您可以手动添加项目或导入电子表格。此数据库将用于自动为您的预算定价。", es: "Gestiona tu lista de precios aquí. Puedes añadir artículos manually o importar una hoja de cálculo. Esta base de datos se utilizará para fijar el precio de tu presupuesto automáticamente.", de: "Verwalten Sie hier Ihre Preisliste. Sie können Artikel manuell hinzufügen oder eine Tabelle importieren. Diese Datenbank wird verwendet, um Ihr Budget automatisch zu preisen." },
    "pricing.addItem": { en: "+ Add Item", pt: "+ Adicionar Item", zh: "+ 添加项目", es: "+ Añadir Artículo", de: "+ Artikel hinzufügen" },
    "pricing.import": { en: "Import from Spreadsheet", pt: "Importar de Planilha", zh: "从电子表格导入", es: "Importar desde Hoja de Cálculo", de: "Aus Tabelle importieren" },
    "pricing.export": { en: "Export to Spreadsheet", pt: "Exportar para Planilha", zh: "导出到电子表格", es: "Exportar a Hoja de Cálculo", de: "In Tabelle exportieren" },
    "pricing.table.description": { en: "Item Description", pt: "Descrição do Item", zh: "项目描述", es: "Descripción del Artículo", de: "Artikelbeschreibung" },
    "pricing.table.unitPrice": { en: "Unit Price (R$)", pt: "Preço Unitário (R$)", zh: "单价 (R$)", es: "Precio Unitario (R$)", de: "Stückpreis (R$)" },
    "pricing.table.noItems": { en: "No items in your pricing database. Add one or import a spreadsheet.", pt: "Nenhum item na sua base de preços. Adicione um ou importe uma planilha.", zh: "您的定价数据库中没有项目。添加一个或导入电子表格。", es: "No hay artículos en tu base de precios. Agrega uno o importa una hoja de cálculo.", de: "Keine Artikel in Ihrer Preisdatenbank. Fügen Sie einen hinzu oder importieren Sie eine Tabelle." },

    "settings.title": { en: "General Settings", pt: "Configurações Gerais", zh: "通用设置", es: "Configuración General", de: "Allgemeine Einstellungen" },
    "settings.financial": { en: "Financial", pt: "Financeiro", zh: "财务", es: "Financiero", de: "Finanzen" },
    "settings.markup": { en: "Markup Percentage (%)", pt: "Percentual de Markup (%)", zh: "加价百分比 (%)", es: "Porcentaje de Margen (%)", de: "Aufschlag in Prozent (%)" },
    "settings.markup.description": { en: "This value is added to the total cost of items to form the final price.", pt: "Este valor é adicionado sobre o custo total dos itens para formar o preço final.", zh: "此值将添加到项目总成本中以形成最终价格。", es: "Este valor se añade al costo total de los artículos para formar el precio final.", de: "Dieser Wert wird zu den Gesamtkosten der Artikel addiert, um den Endpreis zu bilden." },
    "settings.budget": { en: "Budget", pt: "Orçamento", zh: "预算", es: "Presupuesto", de: "Budget" },
    "settings.roundUp": { en: "Round up budget quantity", pt: "Arredondar a quantidade do orçamento para cima", zh: "预算数量向上取整", es: "Redondear la cantidad del presupuesto hacia arriba", de: "Budgetmenge aufrunden" },
    "settings.roundUp.description": { en: "If enabled, any item with a fractional quantity (e.g., 1.5) will be rounded up to the next whole number (2) in the final calculations.", pt: "Se ativado, qualquer item com quantidade fracionada (ex: 1.5) será arredondado para o próximo inteiro (2) nos cálculos finais.", zh: "如果启用，任何带有小数数量的项目（例如 1.5）将在最终计算中向上取整为下一个整数（2）。", es: "Si está habilitado, cualquier artículo con una cantidad fraccional (p. ej., 1.5) se redondeará al siguiente número entero (2) en los cálculos finales.", de: "Wenn aktiviert, wird jeder Artikel mit einer gebrochenen Menge (z. B. 1,5) in den Endberechnungen auf die nächste ganze Zahl (2) aufgerundet." },
    "settings.ai": { en: "AI Assistant", pt: "Assistente (IA)", zh: "AI 助手", es: "Asistente de IA", de: "KI-Assistent" },
    "settings.apiKey.label": { en: "Gemini API Key", pt: "Chave de API Gemini", zh: "Gemini API 密钥", es: "Clave de API de Gemini", de: "Gemini-API-Schlüssel" },
    "settings.apiKey.placeholder": { en: "Paste your API Key here", pt: "Cole sua Chave de API aqui", zh: "在此处粘贴您的 API 密钥", es: "Pega tu clave de API aquí", de: "Fügen Sie hier Ihren API-Schlüssel ein" },
    "settings.apiKey.save": { en: "Save", pt: "Salvar", zh: "保存", es: "Guardar", de: "Speichern" },
    "settings.apiKey.warning": { en: "⚠️ You are not using an API key. Please enter your own key for the AI assistant to work.", pt: "⚠️ Você não está usando uma chave de API. Por favor, insira sua própria chave para que o assistente de IA funcione.", zh: "⚠️ 您未使用 API 密钥。请输入您自己的密钥以使 AI 助手正常工作。", es: "⚠️ No estás utilizando una clave de API. Por favor, introduce tu propia clave para que el asistente de IA funcione.", de: "⚠️ Sie verwenden keinen API-Schlüssel. Bitte geben Sie Ihren eigenen Schlüssel ein, damit der KI-Assistent funktioniert." },
    "settings.apiKey.description": { en: "Required for the chatbot functionality. The key is saved only in your browser for this session and is not shared.", pt: "Necessária para a funcionalidade do chatbot. A chave é salva apenas no seu navegador para esta sessão e não é compartilhada.", zh: "聊天机器人功能所需。该密钥仅保存在您的浏览器中，仅用于此会话，不会被共享。", es: "Requerido para la funcionalidad del chatbot. La clave se guarda solo en tu navegador para esta sesión y no se comparte.", de: "Erforderlich für die Chatbot-Funktionalität. Der Schlüssel wird nur für diese Sitzung in Ihrem Browser gespeichert und nicht weitergegeben." },
    "settings.formulas": { en: "Formula Management", pt: "Gerenciamento de Fórmulas", zh: "公式管理", es: "Gestión de Fórmulas", de: "Formelverwaltung" },
    "settings.formulas.export": { en: "Export Formulas", pt: "Exportar Fórmulas", zh: "导出公式", es: "Exportar Fórmulas", de: "Formeln exportieren" },
    "settings.formulas.import": { en: "Import Formulas", pt: "Importar Fórmulas", zh: "导入公式", es: "Importar Fórmulas", de: "Formeln importieren" },
    "settings.formulas.description": { en: "Save your custom calculation settings or share them with a colleague.", pt: "Salve suas configurações de cálculo personalizadas ou compartilhe com um colega.", zh: "保存您的自定义计算设置或与同事共享。", es: "Guarda tus configuraciones de cálculo personalizadas o compártelas con un colega.", de: "Speichern Sie Ihre benutzerdefinierten Berechnungseinstellungen oder teilen Sie sie mit einem Kollegen." },
    "settings.language": { en: "Language", pt: "Idioma", zh: "语言", es: "Idioma", de: "Sprache" },
    "settings.account.title": { en: "Account", pt: "Conta", zh: "帐户", es: "Cuenta", de: "Konto" },
    "settings.account.loggedInAs": { en: "Logged in as:", pt: "Conectado como:", zh: "登录为：", es: "Conectado como:", de: "Angemeldet als:" },
    "settings.account.logout": { en: "Logout", pt: "Sair", zh: "登出", es: "Cerrar sesión", de: "Abmelden" },
    "settings.account.manageSubscription": { en: "Manage Subscription", pt: "Gerenciar Assinatura", zh: "管理订阅", es: "Gestionar Suscripción", de: "Abonnement verwalten" },
    "settings.account.prompt": { en: "Log in to sync your subscription plan across devices.", pt: "Faça login para sincronizar seu plano de assinatura entre dispositivos.", zh: "登录以在设备间同步您的订阅计划。", es: "Inicia sesión para sincronizar tu plan de suscripción en todos los dispositivos.", de: "Melden Sie sich an, um Ihren Abonnementplan geräteübergreifend zu synchronisieren." },
    "settings.account.loginWithGoogle": { en: "Login with Google", pt: "Login com Google", zh: "使用谷歌登录", es: "Iniciar sesión con Google", de: "Mit Google anmelden" },
    "settings.account.login": { en: "Login", pt: "Entrar", zh: "登录", es: "Iniciar sesión", de: "Anmelden" },
    "settings.account.signup": { en: "Sign Up", pt: "Cadastrar", zh: "注册", es: "Registrarse", de: "Registrieren" },
    "settings.account.email": { en: "Email", pt: "E-mail", zh: "电子邮件", es: "Correo electrónico", de: "E-Mail" },
    "settings.account.password": { en: "Password", pt: "Senha", zh: "密码", es: "Contraseña", de: "Passwort" },
    "settings.account.confirmPassword": { en: "Confirm Password", pt: "Confirmar Senha", zh: "确认密码", es: "Confirmar Contraseña", de: "Passwort bestätigen" },
    "settings.account.or": { en: "OR", pt: "OU", zh: "或", es: "O", de: "ODER" },
    "settings.account.error.passwordsDoNotMatch": { en: "Passwords do not match.", pt: "As senhas não coincidem.", zh: "密码不匹配。", es: "Las contraseñas no coinciden.", de: "Passwörter stimmen nicht überein." },
    
    "chat.welcome": { en: "Hello! How can I help you build your budget today? You can send me a list of items, like '10 screws and 5 nuts', or a floor plan for analysis.", pt: "Olá! Como posso ajudar a montar seu orçamento hoje? Você pode me enviar uma lista de itens, como '10 parafusos e 5 porcas', ou uma planta baixa para análise.", zh: "你好！今天我能如何帮助您建立预算？您可以给我发送一个项目列表，比如“10个螺丝和5个螺母”，或者一个平面图进行分析。", es: "¡Hola! ¿Cómo puedo ayudarte a crear tu presupuesto hoy? Puedes enviarme una lista de artículos, como '10 tornillos y 5 tuercas', o un plano para analizar.", de: "Hallo! Wie kann ich Ihnen heute bei der Erstellung Ihres Budgets helfen? Sie können mir eine Liste von Artikeln schicken, wie '10 Schrauben und 5 Muttern', oder einen Grundriss zur Analyse." },
    "chat.title": { en: "Budget Assistant", pt: "Assistente de Orçamentos", zh: "预算助理", es: "Asistente de Presupuesto", de: "Budget-Assistent" },
    "chat.open": { en: "Open assistant chat", pt: "Abrir chat do assistente", zh: "打开助手聊天", es: "Abrir chat del asistente", de: "Assistenten-Chat öffnen" },
    "chat.close": { en: "Close chat", pt: "Fechar chat", zh: "关闭聊天", es: "Cerrar chat", de: "Chat schließen" },
    "chat.attachFile": { en: "Attach file", pt: "Anexar arquivo", zh: "附加文件", es: "Adjuntar archivo", de: "Datei anhängen" },
    "chat.placeholder": { en: "Send a list or a floor plan...", pt: "Envie uma lista ou uma planta...", zh: "发送列表或平面图...", es: "Envía una lista o un plano...", de: "Senden Sie eine Liste oder einen Grundriss..." },
    "chat.attached": { en: "Attached: {fileName}", pt: "Anexado: {fileName}", zh: "已附加：{fileName}", es: "Adjunto: {fileName}", de: "Angehängt: {fileName}" },
    "chat.noApiKey": { en: "API Key is not configured. Go to the 'Settings' tab to add it.", pt: "A chave de API não está configurada. Vá para a aba 'Configurações' para adicioná-la.", zh: "未配置API密钥。请转到“设置”选项卡添加它。", es: "La clave de API no está configurada. Ve a la pestaña 'Configuración' para agregarla.", de: "API-Schlüssel ist nicht konfiguriert. Gehen Sie zum Tab 'Einstellungen', um ihn hinzuzufügen." },

    "toasts.budgetLoaded": { en: "Budget '{name}' loaded!", pt: "Orçamento '{name}' carregado!", zh: "预算'{name}'已加载！", es: "¡Presupuesto '{name}' cargado!", de: "Budget '{name}' geladen!" },
    "toasts.newBudget": { en: "New budget created. Start adding items!", pt: "Novo orçamento criado. Comece a adicionar itens!", zh: "新预算已创建。开始添加项目！", es: "Nuevo presupuesto creado. ¡Comienza a agregar artículos!", de: "Neues Budget erstellt. Fangen Sie an, Artikel hinzuzufügen!" },
    "toasts.budgetUpdated": { en: "Budget updated successfully!", pt: "Orçamento atualizado com sucesso!", zh: "预算更新成功！", es: "¡Presupuesto actualizado con éxito!", de: "Budget erfolgreich aktualisiert!" },
    "toasts.budgetSaved": { en: "Budget saved successfully!", pt: "Orçamento salvo com sucesso!", zh: "预算保存成功！", es: "¡Presupuesto guardado con éxito!", de: "Budget erfolgreich gespeichert!" },
    "toasts.budgetDeleted": { en: "Budget deleted.", pt: "Orçamento excluído.", zh: "预算已删除。", es: "Presupuesto eliminado.", de: "Budget gelöscht." },
    "toasts.apiKeySaved": { en: "API Key saved for this session.", pt: "Chave de API salva para esta sessão.", zh: "API密钥已为此会话保存。", es: "Clave de API guardada para esta sesión.", de: "API-Schlüssel für diese Sitzung gespeichert." },
    "toasts.apiKeyRemoved": { en: "API Key removed.", pt: "Chave de API removida.", zh: "API密钥已删除。", es: "Clave de API eliminada.", de: "API-Schlüssel entfernt." },
    "toasts.emptyPricingData": { en: "Your pricing database is empty. Add items in the 'Pricing' tab.", pt: "Sua base de preços está vazia. Adicione itens na aba 'Precificação'.", zh: "您的定价数据库为空。请在“定价”选项卡中添加项目。", es: "Tu base de datos de precios está vacía. Agrega artículos en la pestaña 'Precios'.", de: "Ihre Preisdatenbank ist leer. Fügen Sie Artikel im Tab 'Preisgestaltung' hinzu." },
    "toasts.autoPriceSuccess": { en: "{updated} of {total} items have been priced!", pt: "{updated} de {total} itens foram precificados!", zh: "{total}个项目中的{updated}个已定价！", es: "¡Se han preciado {updated} de {total} artículos!", de: "{updated} von {total} Artikeln wurden preiseingegeben!" },
    "toasts.nothingToImport": { en: "No new or modified formulas found to import.", pt: "Nenhuma fórmula nova ou modificada encontrada para importar.", zh: "未找到要导入的新公式或修改过的公式。", es: "No se encontraron fórmulas nuevas o modificadas para importar.", de: "Keine neuen oder geänderten Formeln zum Importieren gefunden." },
    "toasts.importError": { en: "Error reading file: {message}", pt: "Erro ao ler o arquivo: {message}", zh: "读取文件时出错：{message}", es: "Error al leer el archivo: {message}", de: "Fehler beim Lesen der Datei: {message}" },
    "toasts.importSuccess": { en: "Selected formulas imported/updated successfully!", pt: "Fórmulas selecionadas importadas/atualizadas com sucesso!", zh: "所选公式已成功导入/更新！", es: "¡Las fórmulas seleccionadas se importaron/actualizaron con éxito!", de: "Ausgewählte Formeln erfolgreich importiert/aktualisiert!" },
    "toasts.planUpdated": { en: "Your plan has been updated!", pt: "Seu plano foi atualizado!", zh: "您的计划已更新！", es: "¡Tu plan ha sido actualizado!", de: "Ihr Plan wurde aktualisiert!" },
    "toasts.redirectingToCheckout": { en: "Redirecting...", pt: "Redirecionando...", zh: "正在重定向...", es: "Redirigiendo...", de: "Weiterleiten..." },
    "toasts.checkoutNotConfigured": { en: "Checkout is not configured for this plan. Please contact support.", pt: "O checkout não está configurado para este plano. Por favor, entre em contato com o suporte.", zh: "此计划未配置结帐。请联系支持人员。", es: "El pago no está configurado para este plan. Por favor, contacta con soporte.", de: "Die Kasse ist für diesen Plan nicht konfiguriert. Bitte kontaktieren Sie den Support." },
    "toasts.paymentSuccess": { en: "Payment successful! Your plan is now active.", pt: "Pagamento bem-sucedido! Seu plano está ativo.", zh: "支付成功！您的计划现已生效。", es: "¡Pago exitoso! Tu plan ya está activo.", de: "Zahlung erfolgreich! Ihr Plan ist jetzt aktiv." },
    "toasts.paymentCancelled": { en: "Payment cancelled. Your plan was not changed.", pt: "Pagamento cancelado. Seu plano não foi alterado.", zh: "支付已取消。您的计划未更改。", es: "Pago cancelado. Tu plan no ha cambiado.", de: "Zahlung storniert. Ihr Plan wurde nicht geändert." },
    "toasts.portalError": { en: "Could not open management page. Please try again.", pt: "Não foi possível abrir a página de gerenciamento. Tente novamente.", zh: "无法打开管理页面。请再试一次。", es: "No se pudo abrir la página de gestión. Por favor, inténtalo de nuevo.", de: "Verwaltungsseite konnte nicht geöffnet werden. Bitte versuchen Sie es erneut." },

    "ai.calculatedItemsAdded": { en: "{count} calculated item(s) added to the budget.", pt: "{count} item(ns) calculados e adicionados ao orçamento.", zh: "{count}个计算出的项目已添加到预算中。", es: "{count} artículo(s) calculado(s) agregado(s) al presupuesto.", de: "{count} berechnete(r) Artikel zum Budget hinzugefügt." },
    "ai.budgetItemsAdded": { en: "{count} item(s) were added directly.", pt: "{count} item(ns) foram adicionados diretamente.", zh: "{count}个项目已直接添加。", es: "{count} artículo(s) se agregaron directamente.", de: "{count} Artikel wurden direkt hinzugefügt." },
    "ai.noActionTaken": { en: "Understood, but no action was taken. Could you rephrase your request?", pt: "Entendido, mas nenhuma ação foi executada. Pode reformular seu pedido?", zh: "已理解，但未采取任何行动。您能换个说法吗？", es: "Entendido, pero no se tomó ninguna medida. ¿Podrías reformular tu solicitud?", de: "Verstanden, aber es wurde keine Aktion ausgeführt. Könnten Sie Ihre Anfrage neu formulieren?" },
    
    "pdf.defaultTitle": { en: "Budget Proposal", pt: "Proposta de Orçamento", zh: "预算提案", es: "Propuesta de Presupuesto", de: "Angebotsvorschlag" },
    "pdf.defaultHeader": { en: "Budget Proposal", pt: "Proposta de Orçamento", zh: "预算提案", es: "Propuesta de Presupuesto", de: "Angebotsvorschlag" },
    "pdf.defaultFooter": { en: "Proposal valid for 15 days", pt: "Validade da Proposta: 15 dias", zh: "提案有效期15天", es: "Propuesta válida por 15 días", de: "Angebot 15 Tage gültig" },
    "pdf.customize.title": { en: "Customize PDF", pt: "Personalizar PDF", zh: "自定义PDF", es: "Personalizar PDF", de: "PDF anpassen" },
    "pdf.customize.docTitle": { en: "Document Title", pt: "Título do Documento", zh: "文档标题", es: "Título del Documento", de: "Dokumenttitel" },
    "pdf.customize.headerText": { en: "Header Text", pt: "Texto do Cabeçalho", zh: "页眉文本", es: "Texto del Encabezado", de: "Kopfzeilentext" },
    "pdf.customize.footerText": { en: "Footer Text", pt: "Texto do Rodapé", zh: "页脚文本", es: "Texto del Pie de Página", de: "Fußzeilentext" },
    "pdf.customize.primaryColor": { en: "Primary Color", pt: "Cor Primária", zh: "主色", es: "Color Primario", de: "Primärfarbe" },
    "pdf.customize.font": { en: "Font", pt: "Fonte", zh: "字体", es: "Fuente", de: "Schriftart" },
    "pdf.customize.sections": { en: "Sections to Include", pt: "Seções para Incluir", zh: "要包含的部分", es: "Secciones a Incluir", de: "Einzuschließende Abschnitte" },
    "pdf.customize.includeSummary": { en: "Include summary page", pt: "Incluir página de resumo", zh: "包括摘要页面", es: "Incluir página de resumen", de: "Zusammenfassungsseite einschließen" },
    "pdf.customize.includeDetails": { en: "Include details page by sector", pt: "Incluir página de detalhes por setor", zh: "按部门包括详细信息页面", es: "Incluir página de detalles por sector", de: "Detailseite nach Sektor einschließen" },
    "pdf.customize.saveAndClose": { en: "Save and Close", pt: "Salvar e Fechar", zh: "保存并关闭", es: "Guardar y Cerrar", de: "Speichern und Schließen" },

    "import.title": { en: "Import Formulas", pt: "Importar Fórmulas", zh: "导入公式", es: "Importar Fórmulas", de: "Formeln importieren" },
    "import.description": { en: "Select the new or updated formulas you want to add to your app.", pt: "Selecione as fórmulas novas ou atualizadas que você deseja adicionar ao seu aplicativo.", zh: "选择要添加到应用程序的新公式或更新后的公式。", es: "Selecciona las fórmulas nuevas o actualizadas que quieres añadir a tu aplicación.", de: "Wählen Sie die neuen oder aktualisierten Formeln aus, die Sie Ihrer App hinzufügen möchten." },
    "import.selectAll": { en: "Select All", pt: "Selecionar Tudo", zh: "全选", es: "Seleccionar Todo", de: "Alle auswählen" },
    "import.deselectAll": { en: "Deselect All", pt: "Desmarcar Tudo", zh: "取消全选", es: "Deseleccionar Todo", de: "Auswahl aufheben" },
    "import.noChanges": { en: "No new or updated formulas were found in the file.", pt: "Nenhuma fórmula nova ou atualizada foi encontrada no arquivo.", zh: "文件中未找到新的或更新的公式。", es: "No se encontraron fórmulas nuevas o actualizadas en el archivo.", de: "In der Datei wurden keine neuen oder aktualisierten Formeln gefunden." },
    "import.importSelected": { en: "Import Selected", pt: "Importar Selecionados", zh: "导入所选", es: "Importar Seleccionados", de: "Auswahl importieren" },
    "import.status.new": { en: "NEW", pt: "NOVO", zh: "新", es: "NUEVO", de: "NEU" },
    "import.status.updated": { en: "UPDATED", pt: "ATUALIZADO", zh: "已更新", es: "ACTUALIZADO", de: "AKTUALISIERT" },
    "import.invalidFile": { en: "Invalid or corrupted file format.", pt: "Formato de arquivo inválido ou corrompido.", zh: "文件格式无效或已损坏。", es: "Formato de archivo inválido o corrupto.", de: "Ungültiges oder beschädigtes Dateiformat." },
    "budget.table.noSector": { en: "Uncategorized", pt: "Sem Setor", zh: "未分类", es: "Sin Categoría", de: "Nicht kategorisiert" },

    "subscription.title": { en: "Choose Your Plan", pt: "Escolha Seu Plano", zh: "选择您的计划", es: "Elige Tu Plan", de: "Wählen Sie Ihren Plan" },
    "subscription.month": { en: "/month", pt: "/mês", zh: "/月", es: "/mes", de: "/Monat" },
    "subscription.year": { en: "/year", pt: "/ano", zh: "/年", es: "/año", de: "/Jahr" },
    "subscription.currentPlan": { en: "Current Plan", pt: "Plano Atual", zh: "当前计划", es: "Plan Actual", de: "Aktueller Plan" },
    "subscription.selectPlan": { en: "Select Plan", pt: "Selecionar Plano", zh: "选择计划", es: "Seleccionar Plan", de: "Plan auswählen" },
    "subscription.limits": { en: "Limits", pt: "Limites", zh: "限制", es: "Límites", de: "Limits" },
    "subscription.budgets": { en: "{count} budgets", pt: "{count} orçamentos", zh: "{count} 个预算", es: "{count} presupuestos", de: "{count} Budgets" },
    "subscription.itemsPerBudget": { en: "{count} items per budget", pt: "{count} itens por orçamento", zh: "每个预算 {count} 个项目", es: "{count} artículos por presupuesto", de: "{count} Artikel pro Budget" },
    "subscription.unlimited": { en: "Unlimited", pt: "Ilimitado", zh: "无限制", es: "Ilimitado", de: "Unbegrenzt" },
    "subscription.features": { en: "Features", pt: "Funcionalidades", zh: "功能", es: "Características", de: "Funktionen" },
    "subscription.feature.pricing": { en: "Pricing Database", pt: "Base de Precificação", zh: "定价数据库", es: "Base de Precios", de: "Preisdatenbank" },
    "subscription.feature.aiAssistant": { en: "AI Assistant", pt: "Assistente de IA", zh: "AI 助手", es: "Asistente de IA", de: "KI-Assistent" },
    "subscription.feature.importExportFormulas": { en: "Export/Import Formulas", pt: "Exportar/Importar Fórmulas", zh: "导出/导入公式", es: "Exportar/Importar Fórmulas", de: "Formeln exportieren/importieren" },
    "subscription.feature.exportPdfExcel": { en: "Export PDF/Excel", pt: "Exportar PDF/Excel", zh: "导出 PDF/Excel", es: "Exportar PDF/Excel", de: "PDF/Excel exportieren" },
    "subscription.feature.customizePdf": { en: "Customize PDF", pt: "Customizar PDF", zh: "自定义 PDF", es: "Personalizar PDF", de: "PDF anpassen" },
    "subscription.feature.dashboard": { en: "Dashboard with graphics", pt: "Dashboard com gráficos", zh: "带图表的仪表板", es: "Panel con gráficos", de: "Dashboard mit Grafiken" },
    "subscription.feature.addCustomizeFormulas": { en: "Add/Customize Formulas", pt: "Adicionar/Customizar Fórmulas", zh: "添加/自定义公式", es: "Añadir/Personalizar Fórmulas", de: "Formeln hinzufügen/anpassen" },
    "subscription.feature.addGroups": { en: "Add Calculator Groups", pt: "Adicionar Grupos de Cálculo", zh: "添加计算器组", es: "Añadir Grupos de Calculadora", de: "Rechnergruppen hinzufügen" },
    "subscription.feature.addGroupsLimited": { en: "Add Calculator Groups (up to {count})", pt: "Adicionar Grupos de Cálculo (até {count})", zh: "添加计算器组（最多 {count} 个）", es: "Añadir Grupos de Calculadora (hasta {count})", de: "Rechnergruppen hinzufügen (bis zu {count})" },
    "subscription.feature.future": { en: "Access to future features", pt: "Acesso a futuras funcionalidades", zh: "访问未来功能", es: "Acceso a futuras características", de: "Zugang zu zukünftigen Funktionen" },
    "subscription.limit.budgets": { en: "Budget limit of {max} reached. Upgrade your plan to create more.", pt: "Limite de {max} orçamentos atingido. Atualize seu plano para criar mais.", zh: "已达到 {max} 个预算的限制。请升级您的计划以创建更多。", es: "Se alcanzó el límite de {max} presupuestos. Actualiza tu plan para crear más.", de: "Budgetlimit von {max} erreicht. Aktualisieren Sie Ihren Plan, um mehr zu erstellen." },
    "subscription.limit.items": { en: "Item limit of {max} per budget reached. Upgrade your plan to add more.", pt: "Limite de {max} itens por orçamento atingido. Atualize seu plano para adicionar mais.", zh: "每个预算已达到 {max} 个项目的限制。请升级您的计划以添加更多。", es: "Se alcanzó el límite de {max} artículos por presupuesto. Actualiza tu plan para agregar más.", de: "Artikellimit von {max} pro Budget erreicht. Aktualisieren Sie Ihren Plan, um mehr hinzuzufügen." },
    "subscription.limit.groups": { en: "Group limit of {max} reached for the {plan} plan. Upgrade for more groups.", pt: "Limite de {max} grupos atingido para o plano {plan}. Faça um upgrade para ter mais grupos.", zh: "{plan} 计划已达到 {max} 个组的限制。升级以获取更多组。", es: "Se alcanzó el límite de {max} grupos para el plan {plan}. Actualiza para tener más grupos.", de: "Gruppenlimit von {max} für den {plan}-Plan erreicht. Upgraden Sie für mehr Gruppen." },
    "subscription.upgradeRequired.title": { en: "Upgrade Required", pt: "Upgrade Necessário", zh: "需要升级", es: "Se Requiere Actualización", de: "Upgrade erforderlich" },
    "subscription.upgradeRequired.message": { en: "This feature is not available on the {plan} plan. Please upgrade to access it.", pt: "Esta funcionalidade não está disponível no plano {plan}. Por favor, faça um upgrade para acessá-la.", zh: "{plan} 计划不提供此功能。请升级以访问它。", es: "Esta función no está disponible en el plan {plan}. Por favor, actualiza para acceder a ella.", de: "Diese Funktion ist im {plan}-Plan nicht verfügbar. Bitte upgraden Sie, um darauf zuzugreifen." },
    "subscription.billing.monthly": { en: "Monthly", pt: "Mensal", zh: "按月", es: "Mensual", de: "Monatlich" },
    "subscription.billing.annual": { en: "Annual", pt: "Anual", zh: "按年", es: "Anual", de: "Jährlich" },
    "subscription.billing.annualDiscount": { en: "Save ~17%!", pt: "Economize ~17%!", zh: "节省 ~17%！", es: "¡Ahorra ~17%!", de: "Sparen Sie ~17%!" },
    "subscription.lifetime.title": { en: "Lifetime", pt: "Vitalício", zh: "终身", es: "Vitalicio", de: "Lebenslang" },
    "subscription.lifetime.price": { en: "One-time payment", pt: "Pagamento único", zh: "一次性付款", es: "Pago único", de: "Einmalzahlung" },
    "subscription.plan.free": { en: "Free", pt: "Grátis", zh: "免费", es: "Gratis", de: "Kostenlos" },
    "subscription.plan.basic": { en: "Basic", pt: "Básico", zh: "基础版", es: "Básico", de: "Basis" },
    "subscription.plan.basic-plus": { en: "Basic+", pt: "Básico+", zh: "基础+", es: "Básico+", de: "Basic+" },
    "subscription.plan.premium": { en: "Premium", pt: "Premium", zh: "高级版", es: "Premium", de: "Premium" },
    "subscription.plan.lifetime": { en: "Lifetime", pt: "Vitalício", zh: "终身版", es: "Vitalicio", de: "Lebenslang" },
    "subscription.loginRequired": { en: "Please log in to select a plan.", pt: "Por favor, faça login para selecionar um plano.", zh: "请登录以选择计划。", es: "Por favor, inicia sesión para seleccionar un plan.", de: "Bitte melden Sie sich an, um einen Plan auszuwählen." },
    "subscription.bestValue": { en: "Best Value", pt: "Custo-Benefício", zh: "最佳价值", es: "Mejor Valor", de: "Bestes Preis-Leistungs-Verhältnis" }
};

export const getTranslator = (lang: Language) => (key: string, replacements?: { [key: string]: string | number }): string => {
    let translation = translations[key]?.[lang] || translations[key]?.['en'] || key;
    if (replacements) {
        Object.keys(replacements).forEach(rKey => {
            translation = translation.replace(`{${rKey}}`, String(replacements[rKey]));
        });
    }
    return translation;
};